[build]
target = "x86_64-unknown-linux-gnu"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[target.x86_64-unknown-linux-gnu]
linker = "ld.lld"
rustflags = [
    # Build Options
    "-C", "no-redzone=yes",
    "-C", "relocation-model=static",

    # Linker Options
    "-C", "link-arg=--entry=kernel_main",
    "-C", "link-arg=--image-base=0x100000",
    "-C", "link-arg=-nmagic",
    # "-C", "link-arg=-znorelro",
]
